services:
  keycloak:
    build: .
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_PROXY: passthrough
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/taskmanagenow_keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: "true"
      KC_HTTPS_KEY_STORE_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "8080", "--https-port", "7443", "--import-realm"]
    volumes:
      - ./target/user_event_listener-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/user-event-listener.jar
    ports:
      - "8080:8080"
      - "7443:7443"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
